# Generated by Django 5.2.8 on 2026-02-13 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tailor', '0002_remove_measurement_measurements_measurement_ankle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Tailor.customer'),
        ),
    ]
